### DISCUSSION TITLE
Randomly getting failing CORS validation

### DISCUSSION THREAD

**Discussion by ShurikAg** [digitalocean/Kubernetes-Starter-Kit-Developers#119] [Q&A]
After building the environment on Kubernetes we tried migrating our backend to it.
As a result, **sometimes**, CORS check is failing.  

![image](https://user-images.githubusercontent.com/916432/151052149-29179424-fc46-4f36-8152-e54075db3aa1.png)

As per [Ambassador docs](https://www.getambassador.io/docs/edge-stack/latest/topics/using/cors/) we added CORS config to the mapping:

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: priz-api
  namespace: ambassador
spec:
  prefix: /
  host: api.priz.guru
  service: priz-api.backend
  cors:
    origins: https://app.priz.guru
    methods: GET, POST, PUT, PATCH, OPTIONS, DELETE
    headers: "*"
    exposed_headers: "*"
    max_age: "86400"
```

Nothing changed. The most interesting part is that if I initiate the same request again (create a resource), it works!?!?!?

What am I doing wrong? 

Also, the backend API is supporting CORS and it works for years through a regular LB.
What is the best approach here?
