### DISCUSSION TITLE
Kubernetes Nginx Ingress Oauth question

### DISCUSSION THREAD

**Discussion by sonamsamdupkhangsar** [digitalocean/Kubernetes-Starter-Kit-Developers#135] [General]
I am not sure if this is the right place to ask this question but I was curious if you have any ideas about securing an ingress with oauth. 

I have followed your tutorials on setting up Nginx Ingress controller with widlcard certificates for subdomains.  

I am trying to secure my echo.mydomain.com using Oauth with Github application.  
I am following this example from [Nginx documentation for external authentication ](https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/).  

I have the following in my 'ingress-echo.yaml':

```
    nginx.ingress.kubernetes.io/auth-url: "https://echo.sonam.cloud/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://echo.sonam.cloud/oauth2/start?rd=$escaped_request_uri"   
```

When I open echo.sonam.cloud I see 500 errors.  It seems like it doesn't like external https or http endpoints outside of my k8 cluster.  Not sure if you have any ideas.

Thanks

**Comment by sonamsamdupkhangsar** [comment]
Not sure but I am wondering if the issue has already been discussed here with regards to this perhaps?  [Nginx Ingress service](https://github.com/kubernetes/ingress-nginx/issues/3996#issuecomment-566460867)

**Reply by v-ctiutiu** [reply]
Hi @sonamsamdupkhangsar, let me take a look at this and get back to you. Thanks.

**Comment by v-ctiutiu** [comment]
@sonamsamdupkhangsar

Ok, I managed to make it work by following the official [example](https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/). Initially, I was hit by the same issue as yours. Then, I checked the `oauth2` application `deployment`. I noticed that the main application `Pod` was in a `CrashLoopBackOff` state.

```console
kubectl get pods -l  k8s-app=oauth2-proxy -A
```

The output looks similar to:

```text
NAMESPACE     NAME                            READY   STATUS             RESTARTS   AGE
kube-system   oauth2-proxy-56466567bd-b9qfq   0/1     CrashLoopBackOff   7          14m
```

So basically, the `oauth2` backend wasn't working at all. Looking at the main application logs (`kubectl logs -l k8s-app=oauth2-proxy -n kube-system`) I noticed the following error message:

```text
[2022/02/21 08:02:25] [main.go:54] invalid configuration:
  cookie_secret must be 16, 24, or 32 bytes to create an AES cipher, but is 85 bytes
```

Going further, I figured out that I set the `OAUTH2_PROXY_COOKIE_SECRET` environment variable value wrong. Somehow I misunderstood the explanation from the official documentation, meaning the following part (notice the bold text):

> - OAUTH2_PROXY_COOKIE_SECRET **with value of** python -c 'import os,base64; print(base64.b64encode(os.urandom(16)).decode("ascii"))'

You cannot put a piece of executable code in an environment variable from a YAML manifest, and expect for the underlying application to execute it, no ? Going a little bit off topic here - this is a big security risk in general, because we don't want to let users to have the flexibility to execute arbitrary code via environment variables.

So, I went back and `ran` that piece of `python` code in my `terminal`:

```console
python -c 'import os,base64; print(base64.b64encode(os.urandom(16)).decode("ascii"))'
```

**Note:**

The `oauth2` application error code was stating that the `AES cypher` length is `85 bytes`, which is actually the length of the `python code snippet` provided in the documentation page.

Then, I pasted the result in the `OAUTH2_PROXY_COOKIE_SECRET` environment variable. Next, I applied the changes to the `oauht2-proxy` K8S deployment, and the `oauth2` application started to work.

Went back to the web browser, and when I entered the `echo` application URL I was redirected to the GitHub OAuth page. After successfully logging in, the `echo` application response was printed to the screen.

Please let me know how it goes, and if this is the same issue you are facing. 

Thanks.

**Comment by v-ctiutiu** [comment]
Just to be on the same page, here is my `echo` host ingress configured to use `GitHub OAuth`, as well as a `wildcard` TLS certificate:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-echo
  namespace: backend
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://echo.starter-kit.online/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://echo.starter-kit.online/oauth2/start?rd=$escaped_request_uri"
spec:
  tls:
    - hosts:
        - "*.starter-kit.online"
      secretName: starter-kit.online
  rules:
    - host: echo.starter-kit.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo
                port:
                  number: 8080
  ingressClassName: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
    - host: echo.starter-kit.online
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 4180
  tls:
    - hosts:
        - "*.starter-kit.online"
      secretName: starter-kit.online
```

**Reply by sonamsamdupkhangsar** [reply]
Hi @v-ctiutiu 
Thanks so much for replying.  I got it working after updating my subdomain name in the Ingress oauth2-proxy based on what you have shown above.

However, I had to update my Ingress Nginx to get this working by doing a upgrade with my new nginx-values-v4.0.17.yaml values with the following annotation (mydomain is my domain name to replaced): 

```
      service.beta.kubernetes.io/do-loadbalancer-hostname: "www.mydomain.cloud". 

```


My Nginx Ingress values has the following contents now:

```
## Starter Kit nginx configuration
## Ref: https://github.com/kubernetes/ingress-nginx/tree/helm-chart-4.0.13/charts/ingress-nginx
##

controller:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
  service:
    type: LoadBalancer
    annotations:
      # Enable proxy protocol
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
  #     # Specify whether the DigitalOcean Load Balancer should pass encrypted data to backend droplets
      service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
  #     # You can keep your existing LB when migrating to a new DOKS cluster, or when reinstalling AES
      kubernetes.digitalocean.com/load-balancer-id: "<PUT MY LOAD BALANCER ID>"
  #     service.kubernetes.io/do-loadbalancer-disown: false
      service.beta.kubernetes.io/do-loadbalancer-hostname: "www.mydomain.cloud"

  ## See https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/ for notes on enabling and using sysctls
  # sysctls:
  #   "sys.fs.file-max": "1048576"
  #   "net.core.somaxconn": "32768"
  #   "net.ipv4.ip_local_port_range": "1024 65000"

  ## Will add custom configuration options to Nginx https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config:
    use-proxy-protocol: "true"
  #   keep-alive-requests: "10000"
  #   upstream-keepalive-requests: "1000"
  #   worker-processes: "auto"
  #   max-worker-connections: "65535"
  #   use-gzip: "true"
  # Enable the metrics of the NGINX Ingress controller https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/
  metrics:
    enabled: true
  podAnnotations:
    controller:
      metrics:
        service:
          servicePort: "9090"
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
```


Did you have to add that annotation too? 

thanks
-Sonam
