### ISSUE TITLE
Drop function is not working in promtail configuration 

### ISSUE THREAD

**Issue by shreymarkandey-srijan** [digitalocean/Kubernetes-Starter-Kit-Developers#204]
```
promtail:
  enabled: true
  #
  # Enable Promtail service monitoring
  # serviceMonitor:
  #   enabled: true
  #
  # User defined pipeline stages
  pipelineStages:
    - docker: {}
    - drop:
        source: namespace
        expression: "kube-.*"
```
Updating it still kube-system logs are showing in loki & if I replace it with any other NS then also loki is showing it
Bascially when we apply this configuration its not getting updated inside promtail container
